# Generated by Django 5.2.9 on 2026-06-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('noise_floor', models.IntegerField(blank=True, null=True)),
                ('csi_raw', models.TextField()),
                ('prediccion', models.IntegerField(blank=True, null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('modelo_usado', models.CharField(default='rf_3clases', max_length=20)),
            ],
        ),
    ]
